spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://plugger.postgres.database.azure.com:5432/db_fw_rating_service?user=plugger&password=password123-&sslmode=require
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: 'true'
      ddl-auto: update
  security:
    user:
      name: user
      password: password
  application:
    name: fw-rating-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/
  instance:
    hostname: fw-rating-service.azurewebsites.net
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}
security:
  user:
    password: ${eureka.password}

server:
  error:
    include-message: always